
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const UPDATE_INVOICE_STATUS = 'UPDATE_INVOICE_STATUS';
export const CANCEL_INVOICE = 'CANCEL_INVOICE';
export const MARK_AS_PAID = 'MARK_AS_PAID';
export const ADD_TREATMENT_NOTE = 'ADD_TREATMENT_NOTE';
