// src/redux/patientTypes.js

export const PATIENT_UPDATE_PROFIL    = 'PATIENT_UPDATE_PROFIL';
export const PATIENT_RESET_PASSWORD   = 'PATIENT_RESET_PASSWORD';

export const RDV_PATIENT_LOAD         = 'RDV_PATIENT_LOAD';
export const RDV_PATIENT_CREATE       = 'RDV_PATIENT_CREATE';
export const RDV_PATIENT_CANCEL       = 'RDV_PATIENT_CANCEL';

export const DOSSIER_PATIENT_LOAD     = 'DOSSIER_PATIENT_LOAD';
export const FACTURES_PATIENT_LOAD    = 'FACTURES_PATIENT_LOAD';
export const ORDONNANCES_PATIENT_LOAD = 'ORDONNANCES_PATIENT_LOAD';