export const PATIENT_ADD_SUCCESS = "PATIENT_ADD_SUCCESS";
export const PATIENT_UPDATE_SUCCESS = "PATIENT_UPDATE_SUCCESS";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_SET_SEARCH = "PATIENT_SET_SEARCH";

export const RDV_CREATE_SUCCESS = "RDV_CREATE_SUCCESS";
export const RDV_STATUS_SUCCESS = "RDV_STATUS_SUCCESS";
export const RDV_CANCEL_SUCCESS = "RDV_CANCEL_SUCCESS";

export const FACTURE_CREATE_SUCCESS = "FACTURE_CREATE_SUCCESS";
export const FACTURE_SET_FILTRE = "FACTURE_SET_FILTRE";
export const PATIENTS_LOAD_SUCCESS = "PATIENTS_LOAD_SUCCESS";